greeting:
  welcome: Hello Taco World!
server:
  port: 8088
#  ssl:
#    key-store: src/main/resources/mykeys.jks
#    key-store-password: D4uranbek
#    key-password: D4uranbek
logging:
  level:
  tacos: WARN
---
spring:
  profiles:
    active:
      - dev
      - qa
      - prod
  application:
    name: Taco Cloud
    version: 2.0.0
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 671291019398-ahb2l91t1999d6e3cbee4k0q3of64g5j.apps.googleusercontent.com
            clientSecret: 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
            scope: email, public_profile
  thymeleaf:
    cache: false
  data:
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate
      local-datacenter: datacenter1
      port: 9042
      username: cassandra
      password: cassandra
  banner:
    image:
      location: src/main/resources/banner.txt
logging:
  file:
    path: /var/logs/
    file: taco_clod.log
  level:
    tacos: WARN
    root: WARN
    org.springframework.security: DEBUG
taco:
  orders:
    pageSize: 10
    test: test
# todo: set thymeleaf cache true before deployment
# CREATE USER tacocloud WITH PASSWORD 's3cr3tP455w0rd' SUPERUSER;